#!/usr/bin/env python3
"""Regenerates lib/core/bible/bible_books.g.dart.

Downloads KJV-style chapter/verse counts (public domain data from
github.com/aruljohn/Bible-kjv) and writes a const Dart table with the Korean
book names and the 대한성서공회(bskorea.or.kr) book codes used for links.

Usage: python3 tool/generate_bible_books.py
"""
import json
import os
import urllib.parse
import urllib.request

BASE = 'https://raw.githubusercontent.com/aruljohn/Bible-kjv/master/'
CODES = ('GEN EXO LEV NUM DEU JOS JDG RUT 1SA 2SA 1KI 2KI 1CH 2CH EZR NEH EST JOB PSA PRO '
         'ECC SNG ISA JER LAM EZK DAN HOS JOL AMO OBA JON MIC NAM HAB ZEP HAG ZEC MAL MAT MRK '
         'LUK JHN ACT ROM 1CO 2CO GAL EPH PHP COL 1TH 2TH 1TI 2TI TIT PHM HEB JAS 1PE 2PE 1JN '
         '2JN 3JN JUD REV').split()
BSKOREA = ('gen exo lev num deu jos jdg rut 1sa 2sa 1ki 2ki 1ch 2ch ezr neh est job psa pro '
           'ecc sng isa jer lam ezk dan hos jol amo oba jnh mic nam hab zep hag zec mal mat mrk '
           'luk jhn act rom 1co 2co gal eph php col 1th 2th 1ti 2ti tit phm heb jas 1pe 2pe 1jn '
           '2jn 3jn jud rev').split()
KOREAN = ('창세기 출애굽기 레위기 민수기 신명기 여호수아 사사기 룻기 사무엘상 사무엘하 열왕기상 열왕기하 '
          '역대상 역대하 에스라 느헤미야 에스더 욥기 시편 잠언 전도서 아가 이사야 예레미야 예레미야애가 '
          '에스겔 다니엘 호세아 요엘 아모스 오바댜 요나 미가 나훔 하박국 스바냐 학개 스가랴 말라기 '
          '마태복음 마가복음 누가복음 요한복음 사도행전 로마서 고린도전서 고린도후서 갈라디아서 에베소서 '
          '빌립보서 골로새서 데살로니가전서 데살로니가후서 디모데전서 디모데후서 디도서 빌레몬서 히브리서 '
          '야고보서 베드로전서 베드로후서 요한일서 요한이서 요한삼서 유다서 요한계시록').split()


def fetch(name):
    url = BASE + urllib.parse.quote(name)
    return json.loads(urllib.request.urlopen(url).read().decode('utf-8-sig'))


def main():
    books = fetch('Books.json')
    assert len(books) == len(CODES) == len(BSKOREA) == len(KOREAN) == 66
    lines = [
        '// GENERATED by tool/generate_bible_books.py — do not edit by hand.',
        '// Versification: KJV-style chapter/verse counts (source: github.com/aruljohn/Bible-kjv,',
        '// public domain). Korean Protestant translations follow the same versification for',
        '// the passages referenced in this app. 1,189 chapters / 31,102 verses.',
        '',
        "part of 'bible_books.dart';",
        '',
        'const List<BibleBook> kBibleBooks = <BibleBook>[',
    ]
    chapters = verses = 0
    for i, book in enumerate(books):
        data = fetch(book.replace(' ', '') + '.json')
        numbers = [int(c['chapter']) for c in data['chapters']]
        assert numbers == list(range(1, len(numbers) + 1)), book
        counts = [len(c['verses']) for c in data['chapters']]
        chapters += len(counts)
        verses += sum(counts)
        testament = 'oldTestament' if i < 39 else 'newTestament'
        lines.append(
            f"  BibleBook(code: '{CODES[i]}', koreanName: '{KOREAN[i]}', englishName: '{book}', "
            f"bskoreaCode: '{BSKOREA[i]}', testament: Testament.{testament}, "
            f"verseCounts: <int>[{', '.join(map(str, counts))}]),")
    lines.append('];')
    assert (chapters, verses) == (1189, 31102), (chapters, verses)
    out = os.path.join(os.path.dirname(__file__), '..', 'lib', 'core', 'bible', 'bible_books.g.dart')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'wrote {out}: {chapters} chapters, {verses} verses')


if __name__ == '__main__':
    main()
